# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c73818ca128135f40d1f1ec3e8d7e6e2fbd9f4c4d79ca8e612253ca3b70d7ec63c74095342bf5d14a52c6991c133b6f426d0721301891adf50f0961748084e5b

test:
  secret_key_base: b09a2554b58f550cafb4b3ed20c8bc7c6c4fb260c778ef59f036d17c3302d80f3c26e46c4f9c440d4546f98ccc9cadd99f961db0ed1c4f01b7041b6dc16e6748

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
